<?php

namespace App\Services\Database;

use App\Models\DatabaseHost;
use PDO;

/**
 * Creates/drops the actual MySQL database + user for a server's database,
 * on a host the admin registered via DatabaseHostController. Uses a raw
 * PDO connection (not one of Laravel's configured `DB::connection()`s)
 * since the target host is arbitrary and only known at runtime.
 */
class DatabaseProvisioner
{
    public function __construct(private readonly DatabaseHost $host) {}

    /**
     * Confirms the host's stored credentials actually connect - called
     * right after an admin registers a host so a typo fails loudly at
     * creation time instead of silently on the first database request.
     */
    public function ping(): void
    {
        $this->connect();
    }

    public function create(string $database, string $username, string $password, string $remote = '%'): void
    {
        $pdo = $this->connect();

        // Database/user names are generated by us (see
        // ServerDatabaseController), never taken raw from user input, so
        // backtick-quoting them here is safe - MySQL doesn't support
        // parameter binding for identifiers.
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$database}`");

        $stmt = $pdo->prepare('CREATE USER IF NOT EXISTS ?@? IDENTIFIED BY ?');
        $stmt->execute([$username, $remote, $password]);

        $pdo->exec("GRANT ALL PRIVILEGES ON `{$database}`.* TO `{$username}`@`{$remote}`");
        $pdo->exec('FLUSH PRIVILEGES');
    }

    public function drop(string $database, string $username, string $remote = '%'): void
    {
        $pdo = $this->connect();

        $pdo->exec("DROP DATABASE IF EXISTS `{$database}`");

        $stmt = $pdo->prepare('DROP USER IF EXISTS ?@?');
        $stmt->execute([$username, $remote]);

        $pdo->exec('FLUSH PRIVILEGES');
    }

    private function connect(): PDO
    {
        return new PDO($this->host->dsn(), $this->host->username, $this->host->password, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        ]);
    }
}
